services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./src/employee-backend
    ports:
      - "5000:5000"
    volumes:
      - ./src/employee-backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"